-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 17:01:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaCoffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaCoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaCoffee` DEFAULT CHARACTER SET utf8 ;
USE `sistemaCoffee` ;

-- -----------------------------------------------------
-- Table `sistemaCoffee`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`Empleado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `nomina` INT NULL,
  `fecha` DATE NULL,
  `nPeriodos` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`Horario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dia` DATE NULL,
  `horasT` INT NULL,
  `pagoH` DECIMAL(10,2) NULL,
  `idEmpleado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `idEmpleado`),
  INDEX `fk_Horario_Empleado1_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `sistemaCoffee`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`Requisicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`Requisicion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroR` INT NULL,
  `fecha` DATE NULL,
  `departamento` VARCHAR(45) NULL,
  `numeroP` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`Materiales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `descripcion` VARCHAR(100) NULL,
  `precioU` DECIMAL(10,2) NULL,
  `idRequisicion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Materiales_Requisicion1_idx` (`idRequisicion` ASC) VISIBLE,
  CONSTRAINT `fk_Materiales_Requisicion1`
    FOREIGN KEY (`idRequisicion`)
    REFERENCES `sistemaCoffee`.`Requisicion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`TasaGIF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`TasaGIF` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `presupuesto` DECIMAL(10,2) NULL,
  `horasMOD` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`Cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `numeroOrden` INT NULL,
  `descripcion` VARCHAR(100) NULL,
  `cantidad` INT NULL,
  `fechaInicio` DATE NULL,
  `fechaTermino` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCoffee`.`hojaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCoffee`.`hojaC` (
  `id` INT NOT NULL,
  `manoOD` DECIMAL(10,2) NULL,
  `materiales` DECIMAL(10,2) NULL,
  `gif` DECIMAL(10,2) NULL,
  `costoT` DECIMAL(10,2) NULL,
  `costoU` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
