/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class JPRequisicionM extends javax.swing.JPanel {
    ConexionSQL connect = new ConexionSQL();
    Connection con;
    Statement st;
    ResultSet rs;
    DefaultTableModel modeloMateriales;
    String iniciarT = "BEGIN";
    /**
     * Creates new form JPRequisicion
     */
    public JPRequisicionM() throws SQLException {
        initComponents();
        consultaInicial();
        consultaRequisicion();
        consultaCostoT();
    }
    
    public void consultaInicial(){
        try{
            String consultaE = "SELECT cantidad, descripcion, precioU, (cantidad * precioU) AS total FROM materiales";
            con = connect.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(consultaE);
            
            Object[] materiales = new Object[4];
            modeloMateriales = (DefaultTableModel) jTRequisicionM.getModel();
            while(rs.next()){
                materiales[0] = rs.getString("cantidad");
                materiales[1] = rs.getString("descripcion");
                materiales[2] = rs.getString("precioU");
                materiales[3] = rs.getString("total");
                
                modeloMateriales.addRow(materiales);
            }jTRequisicionM.setModel(modeloMateriales);
        }catch(Exception e){
            System.out.println("El error es: "+e);
        }
    }
    
    private void consultaRequisicion() throws SQLException {
        String queryEmpleado = "SELECT numeroR, fecha, departamento, numeroP FROM requisicion";
        try (ResultSet rsEmpleado = st.executeQuery(queryEmpleado)) {
            while (rsEmpleado.next()) {
                String numeroR = rsEmpleado.getString("numeroR");
                String fecha = rsEmpleado.getString("fecha");
                String departemento = rsEmpleado.getString("departamento");
                String numeroP = rsEmpleado.getString("numeroP");
                
                // Asignar los valores a los JLabels correspondientes
                jLNRequisicion.setText(numeroR);
                jLFecha.setText(fecha);
                jLDepartamento.setText(departemento);
                jLNumeroP.setText(numeroP);
            }
        }
    }
    
    private void consultaCostoT() throws SQLException {
        String queryTotalC = "SELECT SUM(cantidad * precioU) AS costoT FROM materiales";
        ResultSet rsTotalC = st.executeQuery(queryTotalC);

        if (rsTotalC.next()) {
            String costoTC = rsTotalC.getString("costoT");
            jLCostoT.setText(costoTC);
        }

        rsTotalC.close();
    }
    
    private void limpiarjLAbelRequisicion(){
        jLNRequisicion.setText("");
        jLFecha.setText("");
        jLDepartamento.setText("");
        jLNumeroP.setText("");
    }
    
    private void limpiarjTFieldRequisicion() {
        jTFNumeroR.setText("Numero de requisición");
        jTFFecha.setText("Fecha Año/Mes/Dia");
        jTFDepartamento.setText("Departamento");
        jTFNumeroP.setText("N° periodo");
    }
    private void limpiarjTFieldMateriales() {
        jTFCantidad.setText("Cantidad");
        jTFDescripcion.setText("Descripcion");
        jTFPrecioU.setText("Precio Unitario");
    }
    
    void limpiarTabla() {
        for (int i = 0; i < jTRequisicionM.getRowCount(); i++) {
            modeloMateriales.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFNumeroR = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTFDepartamento = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTFNumeroP = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTFDescripcion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTFPrecioU = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLNRequisicion = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLDepartamento = new javax.swing.JLabel();
        jLNumeroP = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jBEliminar = new javax.swing.JButton();
        jBAgregarInfo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRequisicionM = new javax.swing.JTable();
        jBAgregarMateriales = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLCostoT = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jBEliminarRegistro = new javax.swing.JButton();
        jBActualizarRegistro = new javax.swing.JButton();

        jPBackground.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(175, 175, 175));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTFNumeroR.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFNumeroR.setText("Numero de requisición");
        jTFNumeroR.setBorder(null);
        jTFNumeroR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNumeroRMousePressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel1.setText("Información");

        jTFFecha.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFFecha.setText("Fecha Año/Mes/Dia");
        jTFFecha.setBorder(null);
        jTFFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFFechaMousePressed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jTFDepartamento.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFDepartamento.setText("Departamento");
        jTFDepartamento.setBorder(null);
        jTFDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFDepartamentoMousePressed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jTFNumeroP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFNumeroP.setText("N° periodo");
        jTFNumeroP.setBorder(null);
        jTFNumeroP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNumeroPMousePressed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel2.setText("Materiales");

        jTFCantidad.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFCantidad.setText("Cantidad");
        jTFCantidad.setBorder(null);
        jTFCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFCantidadMousePressed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jTFDescripcion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFDescripcion.setText("Descripcion");
        jTFDescripcion.setBorder(null);
        jTFDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFDescripcionMousePressed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jTFPrecioU.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFPrecioU.setText("Precio Unitario");
        jTFPrecioU.setBorder(null);
        jTFPrecioU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFPrecioUMousePressed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setText("Numero de requisición:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("Departamento:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("Numero de periodo:");

        jLNRequisicion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLFecha.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLDepartamento.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLNumeroP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jSeparator9.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jBEliminar.setBackground(new java.awt.Color(221, 66, 62));
        jBEliminar.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setText("ELIMINAR");
        jBEliminar.setBorderPainted(false);
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEliminarMouseExited(evt);
            }
        });
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBAgregarInfo.setBackground(new java.awt.Color(12, 147, 81));
        jBAgregarInfo.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBAgregarInfo.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarInfo.setText("AGREGAR");
        jBAgregarInfo.setBorderPainted(false);
        jBAgregarInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgregarInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgregarInfoMouseExited(evt);
            }
        });
        jBAgregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(114, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLNRequisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAgregarInfo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEliminar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLNRequisicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLNumeroP))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBAgregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator9))
                .addContainerGap())
        );

        jTRequisicionM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario", "Total"
            }
        ));
        jTRequisicionM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTRequisicionMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTRequisicionM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jBAgregarMateriales.setBackground(new java.awt.Color(12, 147, 81));
        jBAgregarMateriales.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBAgregarMateriales.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarMateriales.setText("AGREGAR");
        jBAgregarMateriales.setBorderPainted(false);
        jBAgregarMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgregarMaterialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgregarMaterialesMouseExited(evt);
            }
        });
        jBAgregarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarMaterialesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel7.setText("Costo total:  $");

        jLCostoT.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jBLimpiar.setBackground(new java.awt.Color(61, 103, 221));
        jBLimpiar.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBLimpiar.setText("LIMPIAR");
        jBLimpiar.setBorderPainted(false);
        jBLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseExited(evt);
            }
        });
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBEliminarRegistro.setBackground(new java.awt.Color(221, 66, 62));
        jBEliminarRegistro.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBEliminarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminarRegistro.setText("ELIMINAR");
        jBEliminarRegistro.setBorderPainted(false);
        jBEliminarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEliminarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEliminarRegistroMouseExited(evt);
            }
        });
        jBEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarRegistroActionPerformed(evt);
            }
        });

        jBActualizarRegistro.setBackground(new java.awt.Color(1, 168, 168));
        jBActualizarRegistro.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBActualizarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jBActualizarRegistro.setText("ACTUALIZAR");
        jBActualizarRegistro.setBorderPainted(false);
        jBActualizarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBActualizarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBActualizarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBActualizarRegistroMouseExited(evt);
            }
        });
        jBActualizarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBackgroundLayout = new javax.swing.GroupLayout(jPBackground);
        jPBackground.setLayout(jPBackgroundLayout);
        jPBackgroundLayout.setHorizontalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addComponent(jBAgregarMateriales)
                        .addGap(18, 18, 18)
                        .addComponent(jBActualizarRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarRegistro))
                    .addComponent(jTFPrecioU)
                    .addComponent(jTFDescripcion)
                    .addComponent(jTFCantidad)
                    .addComponent(jTFNumeroP)
                    .addComponent(jTFDepartamento)
                    .addComponent(jTFFecha)
                    .addComponent(jTFNumeroR)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator8))
                .addGap(60, 60, 60)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLCostoT))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBLimpiar))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPBackgroundLayout.setVerticalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackgroundLayout.createSequentialGroup()
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNumeroR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPBackgroundLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLCostoT))
                    .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAgregarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBActualizarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarInfoMouseEntered
        jBAgregarInfo.setBackground(new Color(5,102,55));
    }//GEN-LAST:event_jBAgregarInfoMouseEntered

    private void jBAgregarInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarInfoMouseExited
        jBAgregarInfo.setBackground(new Color(12,147,81));
    }//GEN-LAST:event_jBAgregarInfoMouseExited

    private void jBAgregarMaterialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesMouseEntered
        jBAgregarMateriales.setBackground(new Color(5,102,55));
    }//GEN-LAST:event_jBAgregarMaterialesMouseEntered

    private void jBAgregarMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesMouseExited
        jBAgregarMateriales.setBackground(new Color(12,147,81));
    }//GEN-LAST:event_jBAgregarMaterialesMouseExited

    private void jBEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseEntered
        jBEliminar.setBackground(new Color(182,45,41));
    }//GEN-LAST:event_jBEliminarMouseEntered

    private void jBEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseExited
        jBEliminar.setBackground(new Color(221,66,62));
    }//GEN-LAST:event_jBEliminarMouseExited

    private void jTFNumeroRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNumeroRMousePressed
        if(jTFNumeroR.getText().equals("Numero de requisición")){
            jTFNumeroR.setText("");
        }
        
        if(jTFFecha.getText().isEmpty()){
            jTFFecha.setText("Fecha Año/Mes/Dia");
        }
        
        if(jTFDepartamento.getText().isEmpty()){
            jTFDepartamento.setText("Departamento");
        }
        
        if(jTFNumeroP.getText().isEmpty()){
            jTFNumeroP.setText("N° periodo");
        }
    }//GEN-LAST:event_jTFNumeroRMousePressed

    private void jTFFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFFechaMousePressed
        if(jTFNumeroR.getText().isEmpty()){
            jTFNumeroR.setText("Numero de requisición");
        }
        
        if(jTFFecha.getText().equals("Fecha Año/Mes/Dia")){
            jTFFecha.setText("");
        }
        
        if(jTFDepartamento.getText().isEmpty()){
            jTFDepartamento.setText("Departamento");
        }
        
        if(jTFNumeroP.getText().isEmpty()){
            jTFNumeroP.setText("N° periodo");
        }
    }//GEN-LAST:event_jTFFechaMousePressed

    private void jTFDepartamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDepartamentoMousePressed
        if(jTFNumeroR.getText().isEmpty()){
            jTFNumeroR.setText("Numero de requisición");
        }
        
        if(jTFFecha.getText().isEmpty()){
            jTFFecha.setText("Fecha Año/Mes/Dia");
        }
        
        if(jTFDepartamento.getText().equals("Departamento")){
            jTFDepartamento.setText("");
        }
        
        if(jTFNumeroP.getText().isEmpty()){
            jTFNumeroP.setText("N° periodo");
        }
    }//GEN-LAST:event_jTFDepartamentoMousePressed

    private void jTFNumeroPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNumeroPMousePressed
        if(jTFNumeroR.getText().isEmpty()){
            jTFNumeroR.setText("Numero de requisición");
        }
        
        if(jTFFecha.getText().isEmpty()){
            jTFFecha.setText("Fecha Año/Mes/Dia");
        }
        
        if(jTFDepartamento.getText().isEmpty()){
            jTFDepartamento.setText("Departamento");
        }
        
        if(jTFNumeroP.getText().equals("N° periodo")){
            jTFNumeroP.setText("");
        }
    }//GEN-LAST:event_jTFNumeroPMousePressed

    private void jTFCantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCantidadMousePressed
        if(jTFCantidad.getText().equals("Cantidad")){
            jTFCantidad.setText("");
        }
        
        if(jTFDescripcion.getText().isEmpty()){
            jTFDescripcion.setText("Descripcion");
        }
        
        if(jTFPrecioU.getText().isEmpty()){
            jTFPrecioU.setText("Precio Unitario");
        }
    }//GEN-LAST:event_jTFCantidadMousePressed

    private void jTFDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDescripcionMousePressed
        if(jTFCantidad.getText().isEmpty()){
            jTFCantidad.setText("Cantidad");
        }
        
        if(jTFDescripcion.getText().equals("Descripcion")){
            jTFDescripcion.setText("");
        }
        
        if(jTFPrecioU.getText().isEmpty()){
            jTFPrecioU.setText("Precio Unitario");
        }
    }//GEN-LAST:event_jTFDescripcionMousePressed

    private void jTFPrecioUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFPrecioUMousePressed
        if(jTFCantidad.getText().isEmpty()){
            jTFCantidad.setText("Cantidad");
        }
        
        if(jTFDescripcion.getText().isEmpty()){
            jTFDescripcion.setText("Descripcion");
        }
        
        if(jTFPrecioU.getText().equals("Precio Unitario")){
            jTFPrecioU.setText("");
        }
    }//GEN-LAST:event_jTFPrecioUMousePressed

    private void jBAgregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarInfoActionPerformed
        String numeroR = jTFNumeroR.getText();
        String fecha = jTFFecha.getText();
        String departamento = jTFDepartamento.getText();
        String numeroP = jTFNumeroP.getText();
        
        String queryInsert = "INSERT INTO requisicion (id, numeroR, fecha, departamento, numeroP) VALUES (1, "+numeroR+", '"+fecha+"', '"+departamento+"', "+numeroP+")";
        
        if (numeroR.equals("Numero de requisición") && fecha.equals("Fecha Año/Mes/Dia") && departamento.equals("Departamento") && numeroP.equals("N° periodo")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos, porfavor");
        } else if (numeroR.equals("Numero de requisición") || fecha.equals("Fecha Año/Mes/Dia") || departamento.equals("Departamento") || numeroP.equals("N° periodo")) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes, por favor");
        } else {
            try {
                con = connect.getConnection();
                st = con.createStatement();
                st.execute(iniciarT);
                st.executeUpdate(queryInsert);
                JOptionPane.showMessageDialog(null, "Registro agregado");
                con.commit();
                
                limpiarTabla();
                limpiarjTFieldRequisicion();
                consultaRequisicion();
                consultaInicial();
                consultaCostoT();
            } catch (SQLException e) {
                System.out.println("Error: " + e);
                if(con != null){
                    try {
                        JOptionPane.showMessageDialog(null, "Deshaciendo Cambios, usuarios maximos alcanzados");
                        con.rollback();
                        limpiarjTFieldRequisicion();
                        consultaRequisicion();
                        consultaInicial();
                        consultaCostoT();
                    } catch (SQLException ex) {
                        System.out.println("Error: "+ex);
                    }
                }
            } finally {
                try {
                    if (st != null && con != null) {
                        con.setAutoCommit(true);
                        st.close();
                        con.close();
                    }   
                } catch (SQLException e) {
                    System.out.println("Error al cerrar "+e);
                }
            }
        }
    }//GEN-LAST:event_jBAgregarInfoActionPerformed

    private void jBAgregarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesActionPerformed
        String cantidad = jTFCantidad.getText();
        String descripcion = jTFDescripcion.getText();
        String precioU = jTFPrecioU.getText();
        
        String queryInsert = "INSERT INTO materiales (cantidad, descripcion, precioU, idRequisicion) VALUES ("+cantidad+", '"+descripcion+"', "+precioU+", 1)";
        
        if (cantidad.equals("Cantidad") && descripcion.equals("Descripcion") && precioU.equals("Precio Unitario")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos, porfavor");
        } else if (cantidad.equals("Cantidad") || descripcion.equals("Descripcion") || precioU.equals("Precio Unitario")) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes, por favor");
        } else {
            try {
                con = connect.getConnection();
                st = con.createStatement();
                st.execute(iniciarT);
                st.executeUpdate(queryInsert);
                JOptionPane.showMessageDialog(null, "Registro agregado");
                con.commit();
                
                limpiarTabla();
                limpiarjTFieldMateriales();
                consultaRequisicion();
                consultaInicial();
                consultaCostoT();
            } catch (SQLException e) {
                System.out.println("Error: " + e);
                if(con != null){
                    try {
                        JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                        con.rollback();
                        limpiarjTFieldMateriales();
                    } catch (SQLException ex) {
                        System.out.println("Error: "+ex);
                    }
                }
            } finally {
                try {
                    if (st != null && con != null) {
                        con.setAutoCommit(true);
                        st.close();
                        con.close();
                    }   
                } catch (SQLException e) {
                    System.out.println("Error al cerrar "+e);
                }
            }
        }
    }//GEN-LAST:event_jBAgregarMaterialesActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        String sqlDeleteM = "DELETE FROM materiales";
        String sqlDeleteR = "DELETE FROM requisicion";
        try {
            con = connect.getConnection();
            st = con.createStatement();
            st.execute(iniciarT);
            st.execute(sqlDeleteM);
            st.execute(sqlDeleteR);
            JOptionPane.showMessageDialog(null, "Registros Eliminados");
            con.commit();
            
            limpiarjLAbelRequisicion();
            limpiarTabla();
            limpiarjTFieldMateriales();
            limpiarjTFieldRequisicion();
            consultaRequisicion();
            consultaInicial();
            consultaCostoT();
        } catch (Exception e) {
            System.out.println("El error fue: " + e);
            if (con != null) {
                try {
                    JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                    con.rollback();
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                }
            }
        } finally {
            try {
                if (st != null && con != null) {
                    con.setAutoCommit(true);
                    st.close();
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println("Error al cerrar " + e);
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseEntered
        jBLimpiar.setBackground(new Color(30,75,203));
    }//GEN-LAST:event_jBLimpiarMouseEntered

    private void jBLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseExited
        jBLimpiar.setBackground(new Color(61,103,221));
    }//GEN-LAST:event_jBLimpiarMouseExited

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        this.limpiarTabla();
        limpiarjTFieldRequisicion();
        this.limpiarjTFieldMateriales();
        this.consultaInicial();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBEliminarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarRegistroMouseEntered
        jBEliminarRegistro.setBackground(new Color(182,45,41));
    }//GEN-LAST:event_jBEliminarRegistroMouseEntered

    private void jBEliminarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarRegistroMouseExited
        jBEliminarRegistro.setBackground(new Color(221,66,62));
    }//GEN-LAST:event_jBEliminarRegistroMouseExited

    private void jBEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarRegistroActionPerformed
        int fila = this.jTRequisicionM.getSelectedRow();
        String cantidad = this.jTRequisicionM.getValueAt(fila, 1).toString();
        String descripcion = this.jTRequisicionM.getValueAt(fila, 2).toString();
        
        String sql = "DELETE FROM materiales WHERE cantidad = " +cantidad+ " AND descripcion = '"+descripcion+"'";
        try {
            con = connect.getConnection();
            st = con.createStatement();
            st.execute(iniciarT);
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            con.commit();
                        
            limpiarjTFieldRequisicion();
            limpiarTabla();
            consultaInicial();
            consultaCostoT();
        } catch (Exception e) {
            System.out.println("El error fue: " + e);
            if (con != null) {
                try {
                    JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                    con.rollback();
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                }
            }
        } finally {
            try {
                if (st != null && con != null) {
                    con.setAutoCommit(true);
                    st.close();
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println("Error al cerrar " + e);
            }
        }
    }//GEN-LAST:event_jBEliminarRegistroActionPerformed

    private void jTRequisicionMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTRequisicionMMouseClicked
        int fila = this.jTRequisicionM.getSelectedRow();
        this.jTFCantidad.setText(this.jTRequisicionM.getValueAt(fila, 0).toString());
        this.jTFDescripcion.setText(this.jTRequisicionM.getValueAt(fila, 1).toString());
        this.jTFPrecioU.setText(this.jTRequisicionM.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_jTRequisicionMMouseClicked

    private void jBActualizarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarRegistroMouseEntered
        jBActualizarRegistro.setBackground(new Color(2,142,142));
    }//GEN-LAST:event_jBActualizarRegistroMouseEntered

    private void jBActualizarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarRegistroMouseExited
        jBActualizarRegistro.setBackground(new Color(0,139,139));
    }//GEN-LAST:event_jBActualizarRegistroMouseExited

    private void jBActualizarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarRegistroActionPerformed
        int fila = this.jTRequisicionM.getSelectedRow();
        int cantidad = Integer.parseInt(this.jTRequisicionM.getValueAt(fila, 0).toString());
        String descripcion = this.jTRequisicionM.getValueAt(fila, 1).toString();
        String cantidad2 = jTFCantidad.getText();
        String descripcion2 = jTFDescripcion.getText();
        String precioU = jTFPrecioU.getText();
        
        String sql = "UPDATE materiales SET cantidad = "+cantidad2+", descripcion = '"+descripcion2+"', precioU = "+precioU+" WHERE cantidad = "+cantidad+" AND descripcion ='"+descripcion+"'";
        
        try {
            con = connect.getConnection();
            st = con.createStatement();
            st.execute(iniciarT);
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Registro Actualizado");
            con.commit();
                        
            limpiarjTFieldRequisicion();
            limpiarTabla();
            consultaInicial();
            consultaCostoT();
        } catch (Exception e) {
            System.out.println("El error fue: " + e);
            if (con != null) {
                try {
                    JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                    con.rollback();
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                }
            }
        } finally {
            try {
                if (st != null && con != null) {
                    con.setAutoCommit(true);
                    st.close();
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println("Error al cerrar " + e);
            }
        }
    }//GEN-LAST:event_jBActualizarRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarRegistro;
    private javax.swing.JButton jBAgregarInfo;
    private javax.swing.JButton jBAgregarMateriales;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarRegistro;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLCostoT;
    private javax.swing.JLabel jLDepartamento;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNRequisicion;
    private javax.swing.JLabel jLNumeroP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFDepartamento;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFNumeroP;
    private javax.swing.JTextField jTFNumeroR;
    private javax.swing.JTextField jTFPrecioU;
    private javax.swing.JTable jTRequisicionM;
    // End of variables declaration//GEN-END:variables
}
