/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class JPTrabajador extends javax.swing.JPanel {
    ConexionSQL connect = new ConexionSQL();
    Connection con;
    Statement st;
    ResultSet rs;
    DefaultTableModel modeloHorario;
    String iniciarT = "BEGIN";
    /**
     * Creates new form JPRequisicion
     */
    public JPTrabajador() throws SQLException {
        initComponents();
        consultaInicial();
        consultaEmpleado();
        consultaCostoT();
    }
    
    private void limpiarjLAbelEmpleado(){
        jLNEmpleado.setText("");
        jLNomina.setText("");
        jLFecha.setText("");
        jLNumeroP.setText("");
    }
    
    private void limpiarjTFieldEmpleado() {
        jTFEmpleado.setText("Nombre del empleado");
        jTFNomina.setText("Nómina");
        jTFFecha.setText("Fecha Año/Mes/Dia");
        jTFNumeroP.setText("N° periodo");
    }
    private void limpiarjTFieldHorario() {
        jTFDia.setText("Dia Año/Mes/Dia");
        jTFHoras.setText("Total de las horas");
        jTFPagoH.setText("Pago por hora");
    }
    
    void limpiarTabla() {
        for (int i = 0; i < jTTrabajadorT.getRowCount(); i++) {
            modeloHorario.removeRow(i);
            i = i - 1;
        }
    }
    
    public void consultaInicial(){
        try{
            String consultaE = "SELECT dia, horasT, pagoH, (horasT * pagoH) AS total FROM horario";
            con = connect.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(consultaE);
            
            Object[] empleados = new Object[4];
            modeloHorario = (DefaultTableModel) jTTrabajadorT.getModel();
            while(rs.next()){
                empleados[0] = rs.getString("dia");
                empleados[1] = rs.getString("horasT");
                empleados[2] = rs.getString("pagoH");
                empleados[3] = rs.getString("total");
                
                modeloHorario.addRow(empleados);
            }jTTrabajadorT.setModel(modeloHorario);
        }catch(Exception e){
            System.out.println("El error es: "+e);
        }
    }
    
    private void consultaEmpleado() throws SQLException {
        String queryEmpleado = "SELECT nombre, nomina, fecha, nPeriodos FROM empleado";
        try (ResultSet rsEmpleado = st.executeQuery(queryEmpleado)) {
            while (rsEmpleado.next()) {
                String nombre = rsEmpleado.getString("nombre");
                String nomina = rsEmpleado.getString("nomina");
                String fecha = rsEmpleado.getString("fecha");
                String numeroP = rsEmpleado.getString("nPeriodos");
                
                // Asignar los valores a los JLabels correspondientes
                jLNEmpleado.setText(nombre);
                jLNomina.setText(nomina);
                jLFecha.setText(fecha);
                jLNumeroP.setText(numeroP);
            }
        }
    }
    
    private void consultaCostoT() throws SQLException {
        String queryTotalC = "SELECT SUM(horasT * pagoH) AS costoT FROM horario";
        ResultSet rsTotalC = st.executeQuery(queryTotalC);

        if (rsTotalC.next()) {
            String costoTC = rsTotalC.getString("costoT");
            jLCostoT.setText(costoTC);
        }

        rsTotalC.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFEmpleado = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTFNomina = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTFFecha = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTFNumeroP = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTFDia = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTFHoras = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTFPagoH = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLNEmpleado = new javax.swing.JLabel();
        jLNomina = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLNumeroP = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jBEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTrabajadorT = new javax.swing.JTable();
        jBAgregarInfo = new javax.swing.JButton();
        jBAgregarMateriales = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLCostoT = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jBEliminarRegistro = new javax.swing.JButton();

        setBackground(new java.awt.Color(246, 246, 246));

        jPBackground.setBackground(new java.awt.Color(246, 246, 246));

        jSeparator1.setForeground(new java.awt.Color(175, 175, 175));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTFEmpleado.setBackground(new java.awt.Color(246, 246, 246));
        jTFEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFEmpleado.setText("Nombre del empleado");
        jTFEmpleado.setBorder(null);
        jTFEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFEmpleadoMousePressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel1.setText("Información");

        jTFNomina.setBackground(new java.awt.Color(246, 246, 246));
        jTFNomina.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFNomina.setText("Nómina");
        jTFNomina.setBorder(null);
        jTFNomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNominaMousePressed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jTFFecha.setBackground(new java.awt.Color(246, 246, 246));
        jTFFecha.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFFecha.setText("Fecha Año/Mes/Dia");
        jTFFecha.setBorder(null);
        jTFFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFFechaMousePressed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jTFNumeroP.setBackground(new java.awt.Color(246, 246, 246));
        jTFNumeroP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFNumeroP.setText("N° periodo");
        jTFNumeroP.setBorder(null);
        jTFNumeroP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNumeroPMousePressed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel2.setText("Horario del trabajador");

        jTFDia.setBackground(new java.awt.Color(246, 246, 246));
        jTFDia.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFDia.setText("Dia Año/Mes/Dia");
        jTFDia.setBorder(null);
        jTFDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFDiaMousePressed(evt);
            }
        });
        jTFDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiaActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jTFHoras.setBackground(new java.awt.Color(246, 246, 246));
        jTFHoras.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFHoras.setText("Total de las horas");
        jTFHoras.setBorder(null);
        jTFHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFHorasMousePressed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jTFPagoH.setBackground(new java.awt.Color(246, 246, 246));
        jTFPagoH.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTFPagoH.setText("Pago por hora");
        jTFPagoH.setBorder(null);
        jTFPagoH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFPagoHMousePressed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setText("Nombre del empleado");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("Nomina:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("Numero de periodo:");

        jLNEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLNomina.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLFecha.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jLNumeroP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jSeparator9.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jBEliminar.setBackground(new java.awt.Color(221, 66, 62));
        jBEliminar.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setText("ELIMINAR");
        jBEliminar.setBorderPainted(false);
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEliminarMouseExited(evt);
            }
        });
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jBEliminar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLNEmpleado))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLNomina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLFecha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLNumeroP))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator9)
                .addContainerGap())
        );

        jTTrabajadorT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Horas", "Pago", "Total"
            }
        ));
        jTTrabajadorT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTrabajadorTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTrabajadorT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jBAgregarInfo.setBackground(new java.awt.Color(12, 147, 81));
        jBAgregarInfo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBAgregarInfo.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarInfo.setText("+");
        jBAgregarInfo.setBorderPainted(false);
        jBAgregarInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgregarInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgregarInfoMouseExited(evt);
            }
        });
        jBAgregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarInfoActionPerformed(evt);
            }
        });

        jBAgregarMateriales.setBackground(new java.awt.Color(12, 147, 81));
        jBAgregarMateriales.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBAgregarMateriales.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarMateriales.setText("+");
        jBAgregarMateriales.setBorderPainted(false);
        jBAgregarMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgregarMaterialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgregarMaterialesMouseExited(evt);
            }
        });
        jBAgregarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarMaterialesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel7.setText("Costo total:  $");

        jLCostoT.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jBLimpiar.setBackground(new java.awt.Color(61, 103, 221));
        jBLimpiar.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jBLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBLimpiar.setText("LIMPIAR");
        jBLimpiar.setBorderPainted(false);
        jBLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseExited(evt);
            }
        });
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBEliminarRegistro.setBackground(new java.awt.Color(221, 66, 62));
        jBEliminarRegistro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBEliminarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminarRegistro.setText("-");
        jBEliminarRegistro.setBorderPainted(false);
        jBEliminarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEliminarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEliminarRegistroMouseExited(evt);
            }
        });
        jBEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBackgroundLayout = new javax.swing.GroupLayout(jPBackground);
        jPBackground.setLayout(jPBackgroundLayout);
        jPBackgroundLayout.setHorizontalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(jSeparator2))
                            .addComponent(jLabel1)
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFNomina)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFFecha)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFNumeroP)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFDia)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFHoras)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBAgregarMateriales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFPagoH, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackgroundLayout.createSequentialGroup()
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAgregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLCostoT))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBLimpiar))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPBackgroundLayout.setVerticalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLCostoT))
                .addGap(32, 32, 32))
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jBAgregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPagoH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAgregarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPBackgroundLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarInfoMouseEntered
        jBAgregarInfo.setBackground(new Color(5,102,55));
    }//GEN-LAST:event_jBAgregarInfoMouseEntered

    private void jBAgregarInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarInfoMouseExited
        jBAgregarInfo.setBackground(new Color(12,147,81));
    }//GEN-LAST:event_jBAgregarInfoMouseExited

    private void jBAgregarMaterialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesMouseEntered
        jBAgregarMateriales.setBackground(new Color(5,102,55));
    }//GEN-LAST:event_jBAgregarMaterialesMouseEntered

    private void jBAgregarMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesMouseExited
        jBAgregarMateriales.setBackground(new Color(12,147,81));
    }//GEN-LAST:event_jBAgregarMaterialesMouseExited

    private void jBEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseEntered
        jBEliminar.setBackground(new Color(182,45,41));
    }//GEN-LAST:event_jBEliminarMouseEntered

    private void jBEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarMouseExited
        jBEliminar.setBackground(new Color(221,66,62));
    }//GEN-LAST:event_jBEliminarMouseExited

    private void jBAgregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarInfoActionPerformed
        String nombreE = jTFEmpleado.getText();
        String nomina = jTFNomina.getText();
        String fecha = jTFFecha.getText();
        String numeroP = jTFNumeroP.getText();
        
        String queryInsert = "INSERT INTO empleado (id, nombre, nomina, fecha, nPeriodos) VALUES (1, '"+nombreE+"', "+nomina+", '"+fecha+"', "+numeroP+")";
        
        if (nombreE.equals("Nombre del empleado") && nomina.equals("Nómina") && fecha.equals("Fecha Mes/Dia/Año") && numeroP.equals("N° periodo")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos, porfavor");
        } else if (nombreE.equals("Nombre del empleado") || nomina.equals("Nómina") || fecha.equals("Fecha Mes/Dia/Año") || numeroP.equals("N° periodo")) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes, por favor");
        } else {
            try {
                con = connect.getConnection();
                st = con.createStatement();
                st.execute(iniciarT);
                st.executeUpdate(queryInsert);
                JOptionPane.showMessageDialog(null, "Registro agregado");
                con.commit();
                
                limpiarTabla();
                limpiarjTFieldEmpleado();
                consultaEmpleado();
                consultaInicial();
                consultaCostoT();
            } catch (SQLException e) {
                System.out.println("Error: " + e);
                if(con != null){
                    try {
                        JOptionPane.showMessageDialog(null, "Deshaciendo Cambios, usuarios maximos alcanzados");
                        con.rollback();
                        limpiarjTFieldEmpleado();
                        consultaEmpleado();
                        consultaInicial();
                        consultaCostoT();
                    } catch (SQLException ex) {
                        System.out.println("Error: "+ex);
                    }
                }
            } finally {
                try {
                    if (st != null && con != null) {
                        con.setAutoCommit(true);
                        st.close();
                        con.close();
                    }   
                } catch (SQLException e) {
                    System.out.println("Error al cerrar "+e);
                }
            }
        }
    }//GEN-LAST:event_jBAgregarInfoActionPerformed

    private void jBAgregarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarMaterialesActionPerformed
        String dia = jTFDia.getText();
        String totalHS = jTFHoras.getText();
        String pagoHS = jTFPagoH.getText();
        
        String queryInsert = "INSERT INTO horario (dia, horasT, pagoH, total, idEmpleado) VALUES ('"+dia+"', "+totalHS+", "+pagoHS+", NULL, 1)";
        
        if (dia.equals("Dia") && totalHS.equals("Total de las horas") && pagoHS.equals("Pago por hora")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos, porfavor");
        } else if (dia.equals("Dia") || totalHS.equals("Total de las horas") || pagoHS.equals("Pago por hora")) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes, por favor");
        } else {
            try {
                con = connect.getConnection();
                st = con.createStatement();
                st.execute(iniciarT);
                st.executeUpdate(queryInsert);
                JOptionPane.showMessageDialog(null, "Registro agregado");
                con.commit();
                
                limpiarTabla();
                limpiarjTFieldHorario();
                consultaEmpleado();
                consultaInicial();
                consultaCostoT();
            } catch (SQLException e) {
                System.out.println("Error: " + e);
                if(con != null){
                    try {
                        JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                        con.rollback();
                        limpiarjTFieldEmpleado();
                    } catch (SQLException ex) {
                        System.out.println("Error: "+ex);
                    }
                }
            } finally {
                try {
                    if (st != null && con != null) {
                        con.setAutoCommit(true);
                        st.close();
                        con.close();
                    }   
                } catch (SQLException e) {
                    System.out.println("Error al cerrar "+e);
                }
            }
        }
    }//GEN-LAST:event_jBAgregarMaterialesActionPerformed

    private void jTFEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFEmpleadoMousePressed
        if (jTFEmpleado.getText().equals("Nombre del empleado")) {
            jTFEmpleado.setText("");
        }
        if (jTFNomina.getText().isEmpty()) {
            jTFNomina.setText("Nómina");   
        }

        if (jTFFecha.getText().isEmpty()) {
            jTFFecha.setText("Fecha Año/Mes/Dia");  
        }

        if (jTFNumeroP.getText().isEmpty()) {
            jTFNumeroP.setText("N° periodo");  
        }
    }//GEN-LAST:event_jTFEmpleadoMousePressed

    private void jTFNominaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNominaMousePressed
        if (jTFEmpleado.getText().isEmpty()) {
            jTFEmpleado.setText("Nombre del empleado");
        }

        if (jTFNomina.getText().equals("Nómina")) {
            jTFNomina.setText("");
        }
        
        if (jTFFecha.getText().isEmpty()) {
            jTFFecha.setText("Fecha Año/Mes/Dia");
        }

        if (jTFNumeroP.getText().isEmpty()) {
            jTFNumeroP.setText("N° periodo");
        }
    }//GEN-LAST:event_jTFNominaMousePressed

    private void jTFFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFFechaMousePressed
        if (jTFEmpleado.getText().isEmpty()) {
            jTFEmpleado.setText("Nombre del empleado");
        }

        if (jTFNomina.getText().isEmpty()) {
            jTFNomina.setText("Nómina");
        }

        if (jTFFecha.getText().equals("Fecha Año/Mes/Dia")) {
            jTFFecha.setText("");
        }

        if (jTFNumeroP.getText().isEmpty()) {
            jTFNumeroP.setText("N° periodo");
        }
    }//GEN-LAST:event_jTFFechaMousePressed

    private void jTFNumeroPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNumeroPMousePressed
        if (jTFEmpleado.getText().isEmpty()) {
            jTFEmpleado.setText("Nombre del empleado");
        }

        if (jTFNomina.getText().isEmpty()) {
            jTFNomina.setText("Nómina");
        }

        if (jTFFecha.getText().isEmpty()) {
            jTFFecha.setText("Fecha Año/Mes/Dia");
        }

        if (jTFNumeroP.getText().equals("N° periodo")) {
            jTFNumeroP.setText("");
        }
    }//GEN-LAST:event_jTFNumeroPMousePressed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        String sqlDeleteH = "DELETE FROM horario";
        String sqlDeleteE = "DELETE FROM Empleado";
        try {
            con = connect.getConnection();
            st = con.createStatement();
            st.execute(iniciarT);
            st.execute(sqlDeleteH);
            st.execute(sqlDeleteE);
            JOptionPane.showMessageDialog(null, "Registros Eliminados");
            con.commit();
            
            limpiarjLAbelEmpleado();
            limpiarTabla();
            limpiarjTFieldHorario();
            limpiarjTFieldEmpleado();
            consultaEmpleado();
            consultaInicial();
            consultaCostoT();
        } catch (Exception e) {
            System.out.println("El error fue: " + e);
            if (con != null) {
                try {
                    JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                    con.rollback();
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                }
            }
        } finally {
            try {
                if (st != null && con != null) {
                    con.setAutoCommit(true);
                    st.close();
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println("Error al cerrar " + e);
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTFDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDiaMousePressed
        if (jTFDia.getText().equals("Dia Año/Mes/Dia")) {
            jTFDia.setText("");
        }
        if (jTFHoras.getText().isEmpty()) {
            jTFHoras.setText("Total de las horas");   
        }

        if (jTFPagoH.getText().isEmpty()) {
            jTFPagoH.setText("Pago por hora");  
        }
    }//GEN-LAST:event_jTFDiaMousePressed

    private void jTFHorasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFHorasMousePressed
        if (jTFDia.getText().isEmpty()) {
            jTFDia.setText("Dia Año/Mes/Dia");
        }
        if (jTFHoras.getText().equals("Total de las horas")) {
            jTFHoras.setText("");   
        }

        if (jTFPagoH.getText().isEmpty()) {
            jTFPagoH.setText("Pago por hora");  
        }
    }//GEN-LAST:event_jTFHorasMousePressed

    private void jTFPagoHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFPagoHMousePressed
        if (jTFDia.getText().isEmpty()) {
            jTFDia.setText("Dia Año/Mes/Dia");
        }
        if (jTFHoras.getText().isEmpty()) {
            jTFHoras.setText("Total de las horas");   
        }

        if (jTFPagoH.getText().equals("Pago por hora")) {
            jTFPagoH.setText("");  
        }
    }//GEN-LAST:event_jTFPagoHMousePressed

    private void jBLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseEntered
        jBLimpiar.setBackground(new Color(30,75,203));
    }//GEN-LAST:event_jBLimpiarMouseEntered

    private void jBLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseExited
        jBLimpiar.setBackground(new Color(61,103,221));
    }//GEN-LAST:event_jBLimpiarMouseExited

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        this.limpiarTabla();
        limpiarjTFieldEmpleado();
        this.limpiarjTFieldHorario();
        this.consultaInicial();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBEliminarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarRegistroMouseEntered
        jBEliminarRegistro.setBackground(new Color(182,45,41));
    }//GEN-LAST:event_jBEliminarRegistroMouseEntered

    private void jBEliminarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminarRegistroMouseExited
        jBEliminarRegistro.setBackground(new Color(221,66,62));
    }//GEN-LAST:event_jBEliminarRegistroMouseExited

    private void jBEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarRegistroActionPerformed
        int fila = this.jTTrabajadorT.getSelectedRow();
        String dia = this.jTTrabajadorT.getValueAt(fila, 0).toString();
        int horasT = Integer.parseInt(this.jTTrabajadorT.getValueAt(fila, 1).toString());
        String sql = "DELETE FROM horario WHERE dia = '" +dia+ "' AND horasT = "+horasT;
        try {
            con = connect.getConnection();
            st = con.createStatement();
            st.execute(iniciarT);
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            con.commit();
                        
            limpiarjTFieldEmpleado();
            limpiarTabla();
            consultaInicial();
            consultaCostoT();
        } catch (Exception e) {
            System.out.println("El error fue: " + e);
            if (con != null) {
                try {
                    JOptionPane.showMessageDialog(null, "Deshaciendo Cambios");
                    con.rollback();
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                }
            }
        } finally {
            try {
                if (st != null && con != null) {
                    con.setAutoCommit(true);
                    st.close();
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println("Error al cerrar " + e);
            }
        }
    }//GEN-LAST:event_jBEliminarRegistroActionPerformed

    private void jTTrabajadorTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTrabajadorTMouseClicked
        int fila = this.jTTrabajadorT.getSelectedRow();
        this.jTFDia.setText(this.jTTrabajadorT.getValueAt(fila, 0).toString());
        this.jTFHoras.setText(this.jTTrabajadorT.getValueAt(fila, 1).toString());
        this.jTFPagoH.setText(this.jTTrabajadorT.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_jTTrabajadorTMouseClicked

    private void jTFDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarInfo;
    private javax.swing.JButton jBAgregarMateriales;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarRegistro;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLCostoT;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNEmpleado;
    private javax.swing.JLabel jLNomina;
    private javax.swing.JLabel jLNumeroP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFDia;
    private javax.swing.JTextField jTFEmpleado;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFHoras;
    private javax.swing.JTextField jTFNomina;
    private javax.swing.JTextField jTFNumeroP;
    private javax.swing.JTextField jTFPagoH;
    private javax.swing.JTable jTTrabajadorT;
    // End of variables declaration//GEN-END:variables
}
