/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Views.JPHojaCostos;
import Views.JPInicio;
import Views.JPRequisicion;
import Views.JPTasaGIF;
import Views.JPTrabajador;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        initContent();
    }
    
    private void initContent(){
        JPInicio vinicio = new JPInicio();
        vinicio.setSize(1012, 590);
        vinicio.setLocation(0,0);
        
        jPViews.removeAll();
        jPViews.add(vinicio, BorderLayout.CENTER);
        jPViews.revalidate();
        jPViews.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenu = new javax.swing.JPanel();
        jBRequisicionM = new javax.swing.JButton();
        jBTiempoT = new javax.swing.JButton();
        jBTasaGIF = new javax.swing.JButton();
        jBHojaC = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPViews = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPMenu.setBackground(new java.awt.Color(236, 236, 236));

        jBRequisicionM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RequisicionM.png"))); // NOI18N
        jBRequisicionM.setToolTipText("Requisición de materiales");
        jBRequisicionM.setBorderPainted(false);
        jBRequisicionM.setContentAreaFilled(false);
        jBRequisicionM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRequisicionM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRequisicionMActionPerformed(evt);
            }
        });

        jBTiempoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TiempoT.png"))); // NOI18N
        jBTiempoT.setToolTipText("Hoja de tiempo de los trabajadores");
        jBTiempoT.setBorderPainted(false);
        jBTiempoT.setContentAreaFilled(false);
        jBTiempoT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTiempoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTiempoTActionPerformed(evt);
            }
        });

        jBTasaGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TazaGIF.png"))); // NOI18N
        jBTasaGIF.setToolTipText("Calculo de tasa GIF");
        jBTasaGIF.setBorderPainted(false);
        jBTasaGIF.setContentAreaFilled(false);
        jBTasaGIF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTasaGIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTasaGIFActionPerformed(evt);
            }
        });

        jBHojaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HojaC.png"))); // NOI18N
        jBHojaC.setToolTipText("Hoja de costos");
        jBHojaC.setBorderPainted(false);
        jBHojaC.setContentAreaFilled(false);
        jBHojaC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBHojaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHojaCActionPerformed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Salir.png"))); // NOI18N
        jBSalir.setToolTipText("Salir del sistema");
        jBSalir.setBorderPainted(false);
        jBSalir.setContentAreaFilled(false);
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COFFEE");

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBRequisicionM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBTiempoT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBTasaGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBHojaC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jBRequisicionM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jBTiempoT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jBTasaGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jBHojaC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPViewsLayout = new javax.swing.GroupLayout(jPViews);
        jPViews.setLayout(jPViewsLayout);
        jPViewsLayout.setHorizontalGroup(
            jPViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPViewsLayout.setVerticalGroup(
            jPViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPViews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPViews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRequisicionMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRequisicionMActionPerformed
        JPRequisicion vRequisicion = new JPRequisicion();
        vRequisicion.setSize(1012, 543);
        vRequisicion.setLocation(0,0);
        
        jPViews.removeAll();
        jPViews.add(vRequisicion, BorderLayout.CENTER);
        jPViews.revalidate();
        jPViews.repaint();
    }//GEN-LAST:event_jBRequisicionMActionPerformed

    private void jBTiempoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTiempoTActionPerformed
        try {
            JPTrabajador vTiempoT = new JPTrabajador();
            vTiempoT.setSize(1012, 543);
            vTiempoT.setLocation(0,0);
            
            jPViews.removeAll();
            jPViews.add(vTiempoT, BorderLayout.CENTER);
            jPViews.revalidate();
            jPViews.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(JFMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTiempoTActionPerformed

    private void jBTasaGIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTasaGIFActionPerformed
        JPTasaGIF vTasaGIF = new JPTasaGIF();
        vTasaGIF.setSize(1012, 543);
        vTasaGIF.setLocation(0,0);
        
        jPViews.removeAll();
        jPViews.add(vTasaGIF, BorderLayout.CENTER);
        jPViews.revalidate();
        jPViews.repaint();
    }//GEN-LAST:event_jBTasaGIFActionPerformed

    private void jBHojaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHojaCActionPerformed
        JPHojaCostos vHojaC = new JPHojaCostos();
        vHojaC.setSize(1012, 590);
        vHojaC.setLocation(0,0);
        
        jPViews.removeAll();
        jPViews.add(vHojaC, BorderLayout.CENTER);
        jPViews.revalidate();
        jPViews.repaint();
    }//GEN-LAST:event_jBHojaCActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        JFLogin vLogin = new JFLogin();
        JOptionPane.showMessageDialog(null, "Hasta luego usuario");
        vLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBHojaC;
    private javax.swing.JButton jBRequisicionM;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBTasaGIF;
    private javax.swing.JButton jBTiempoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPViews;
    // End of variables declaration//GEN-END:variables
}
